### PR TITLE
Use dotenv in Dash app

### LINKED ISSUE #108: dash examples require dotenv to run on workbench
see rstudio/evaluations#401

### PR DESCRIPTION
**Pull request by rstub**
fixes #108

### CODE REVIEW

**Comment by tnederlof** [comment]
The issue I found with this is a deploy to Connect is not heavy. I guess we could make it a condition on whether a Connect env variable is found?

**Comment by rstub** [comment]
Sorry, I am not following. What kind of issue have you seen with this approach?

**Comment by leesahanders** [comment]
@tnederlof wanted to check on this code change, if you could provide a little more information. Thanks!

**Comment by rstub** [comment]
I am curios if this is still needed. Recently I have had the impression that the information from `.env` was now loaded w/o these changes, but I have to investigate this more carefully.

**Comment by leesahanders** [comment]
Added with this PR so that both pieces of dash content were updated: https://github.com/rstudio/posit-demo-assets/pull/124

**Comment by leesahanders** [comment]
Going to close this request as it was resolved with that PR, but please reach out if you have a chance to try it and it didn't look like it did the trick. Thanks for reporting the issue!

**Pull request closed without merging**
